### ISSUE TITLE
[BUG] xPortIsInsideInterrupt missing in Cortex M0

### ISSUE THREAD

**Issue by josesimoes** [FreeRTOS/FreeRTOS-Kernel#58] opened 2020-05-04 14:49 UTC
**Describe the bug**
- The port for Cortex M0 is missing this call.

**Target**
- Development board: 
- Instruction Set Architecture: Cortex M0
- IDE and version: 
- Toolchain and version: 

**Host**
- Host OS: [e.g. MacOS]
- Version: [e.g. Mojave 10.14.6]

**To Reproduce**

**Expected behavior**
- The port for M0 should have this.

**Screenshots**

**Additional context**

**Comment by RichardBarry** [comment] 2020-05-04 19:45
There aren't actually that many ports that have this capability, so this may be considered a feature request rather than bug.  We do already have a feature request (which may even make it into the next release) to allow people to add their own code into the port layers in the same way they are currently able to add their own code into tasks.c using freertos_tasks_c_additions https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/V10.3.1-kernel-only/tasks.c#L5297  That would enable users to add any additional port specific functionality they desired into the code - including functions to let you know whether you are in an interrupt or not.

I have added your request to our backlog, but as this is not a bug in existing code, but a request to add functionality, I will close this bug ticket.

**Closed by RichardBarry** 2020-05-04 19:45 UTC
Labels: bug
