### ISSUE TITLE
[DOC] doxygen warnings using V10.4.6

### ISSUE THREAD

**Issue by tnh8** [FreeRTOS/FreeRTOS-Kernel#450] opened 2022-02-07 14:02 UTC
**Describe the issue**
Building documentation with doxygen produces the following build warnings from FreeRTOS-Kernel:

```
freeRTOS/Source/include/event_groups.h:68: warning: missing title after \defgroup EventGroup
freeRTOS/Source/include/task.h:996: warning: Found unknown command '@xGetFreeStackSpace'
```

**Reference**
Using FreeRTOS-Kernel [V10.4.6](https://github.com/FreeRTOS/FreeRTOS-Kernel/releases/tag/V10.4.6) and doxygen version `1.8.19`

**Comment by muneebahmed10** [comment] 2022-02-08 22:17
Hi @tnh8,

Would you be able to share how you are generating the doxygen documentation? We don't use doxygen to generate our API documentation for this repository, so I'm unable to reproduce the warnings that you're seeing.

Based on your comments, I created PR #453 that I think should fix the issues you've reported. Can you pull that PR and test to see if the warnings are resolved?

**Comment by tnh8** [comment] 2022-02-09 08:26
Hi @muneebahmed10,

Unfortunately it's quite a complex setup of multiple repositories and a custom build system on top of doxygen and I'm not so proficient with doxygen yet. So it's gonna take some time for me to setup a minimal example, similar to our, that I can share.

However I manually took your proposed changes and that fixed the remaining warnings, great! :)

**Comment by muneebahmed10** [comment] 2022-02-10 19:42
Hi @tnh8,

I've gone ahead and merged the PR. Please feel free to open a new issue for any other fixes in documentation. Since you are the one using doxygen, it will likely be faster if you were to test the fix, so pull requests are always welcome.

Thank you

**Closed by muneebahmed10** 2022-02-10 19:42 UTC
Labels: documentation
