### ISSUE TITLE
[DOC]

### ISSUE THREAD

**Issue by duaneellissd** [FreeRTOS/FreeRTOS-Kernel#1171] opened 2024-10-31 15:20 UTC
**Describe the issue**
i notice there are a number of functions, variables and macros that have what i recognize as Hungarian prefixes

ref: https://en.wikipedia.org/wiki/Hungarian_notation

some start with p commonly a pointer but others start with x and v there appears to be some convention that is used.
some usage is understandable and i am familiar with but other items seem very specific to freertos

**examples**

* mtCOVERAGE_TEST_MARKER() - i understand the purpose. but what does mt mean?
* vListTask() the v means what?
* xSuspendedTaskList what is the x for?

what i am suggesting is this:

please provide a table of All “Hungarian notation” prefixes used in freertos and a brief description of their purpose

**Comment by ActoryOu** [comment] 2024-11-01 06:18
Hello @duaneellissd,

Thank you for your inquiry. For naming conventions in FreeRTOS libraries, please consult the [Coding Standard, Testing and Style Guide on the FreeRTOS Website](https://www.freertos.org/Documentation/02-Kernel/06-Coding-guidelines/02-FreeRTOS-Coding-Standard-and-Style-Guide).

To briefly address your examples:
- mtCOVERAGE_TEST_MARKER(): Defined for skipping GCOV code coverage scanning.
- vListTask(): 'v' indicates a void return type.
- xSuspendedTaskList: 'x' denotes custom, non-standard data structures.

We appreciate your interest in FreeRTOS. 
Since the issue is answered, I'm closing the issue. Feel free to re-open or issue a new one if you need further assistance.

Thank you.

**Closed by ActoryOu** 2024-11-01 06:18 UTC
Labels: documentation
